server:
  port: 8090
spring:
  application:
    name: cloud-goods-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
#   rabbitmq




# mybatis查询日志
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  logging:
    level:
      com.yk.controller: debug

  datasource:
    username: root
    password: "020124"
    url: jdbc:mysql://127.0.0.1:3306/compare_price_mall?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    port: 5672

