server:
  port: 8090

spring:
  application:
    name: cloud-goods-service
  # Sentinel配置（属于spring的直接子项）
#  sentinel:
#    transport:
#      dashboard: 127.0.0.1:8858
#      port: 8719
#      client-ip: 127.0.0.1
#    eager: true
#    web-context-unify: false
    datasource:
      ds:
        nacos:
          server-addr: 127.0.0.1:8848
          data-id: ${spring.application.name}-sentinel
          group-id: DEFAULT_GROUP
          rule-type: flow
  # Nacos配置（属于spring.cloud的子项）
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
  # 数据库配置（属于spring的直接子项）
  datasource:
    username: root
    password: "020124"
    url: jdbc:mysql://127.0.0.1:3306/compare_price_mall?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # RabbitMQ配置（属于spring的直接子项）
  rabbitmq:
    host: 127.0.0.1
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        multiplier: 1
        max-attempts: 3
    port: 5672
    # 允许反序列化的类
  # MyBatis配置（属于spring的直接子项）
  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Feign配置（顶级配置，与spring同级）
feign:
  sentinel:
    enabled: true

# 日志配置（顶级配置，与spring同级）
logging:
  level:
    com.yk.controller: debug
    com.alibaba.csp.sentinel: debug
    com.alibaba.csp.sentinel.transport: debug
