server:
  port: 8084

spring:
  main:
    web-application-type: reactive
  application:
    name: cloud-gateway
  sentinel:
    transport:
      dashboard: 127.0.0.1:8868
      port: 8720
      client-ip: 127.0.0.1
    eager: true
    web-context-unify: false
    gateway:
      enabled: true
      api-group:
        enabled: true
      request-group:
        enabled: true
      response-group:
        enabled: true
      exception-group:
        enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        initial-interval: 1000
        multiplier: 1.0
        max-attempts: 3

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: payment_route
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/**
          filters:
            - name: RequestRateLimiter
        - id: user_route
          uri: lb://cloud-login-service
          predicates:
            - Path=/user/**
        - id: post_route
          uri: lb://cloud-forum-service
          predicates:
            - Path=/post/**
        - id: product_route
          uri: lb://cloud-goods-service
          predicates:
            - Path=/product/**

# Enable detailed gateway debug logs
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO

# Expose actuator endpoints for troubleshooting
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"