server:
  port: 8085
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false
  application:
    name: cloud-payment-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
