server:
  port: 8085

spring:
  config:
    import: "nacos:payment-service.yaml"
  application:
    name: cloud-payment-service
  boot:
    admin:
      client:
        url: http://localhost:8788
        instance:
          prefer-ip: true
        username: admin
        password: 123456
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        discovery:
          ip: 127.0.0.1
        file-extension: yaml
        group: DEFAULT_GROUP
        namespace: payment-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  info:
    version: 1.0-SNAPSHOT
    name: payment
    group: org.example
    description: Parent pom providing dependency and plugin management for applications built with Maven
    #还可以自定义信息
    author: yk

