server:
  port: 8087

spring:
  config:
    import: "optional:nacos"
  application:
    name: cloud-login-service
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        initial-interval: 1000
        multiplier: 1.0
        max-attempts: 3

  datasource:
    username: root
    password: "020124"
    url: jdbc:mysql://127.0.0.1:3306/compare_price_mall?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
